// @ts-nocheck
// このファイルは自動生成されます。手編集しないでください（GEN-03）。
// 生成: `pnpm generate:bindings`
// イベント未使用時に生じる未使用シンボルの警告を避けるため型チェック対象から外す。

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * サンプルコマンド。フロントの型付き呼び出し（tauri-specta, RS-05）を実演する。
 */
async greet(name: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * フロントから渡された秘密情報を OS キーチェーンに保存する。保存後は破棄され、
 * 二度とフロントへは返らない（SEC-04, RS-12）。
 */
async saveCredential(account: string, secret: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_credential", { account, secret }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 値そのものではなく「保存されているか」だけをフロントに返す。
 */
async hasCredential(account: string) : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_credential", { account }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCredential(account: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_credential", { account }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * RS-10: 進捗イベントを伴う長時間処理のサンプル。即座にタスク ID を返し、
 * 実処理はバックグラウンドで進める。フロントは `TaskProgress` イベントを購読して
 * 進捗バーを更新し、`cancel_long_task` でキャンセルできる。
 */
async startLongTask(steps: number) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_long_task", { steps }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelLongTask(taskId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_long_task", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * RS-09 のサンプルコマンド。SQL 組み立てとコンパイル時検証は `app_core::domain::notes` 側
 * （`sqlx::query!`）に閉じ、ここでは呼び出しと State からの取得のみを行う。
 */
async createNote(title: string, body: string) : Promise<Result<Note, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_note", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listNotes() : Promise<Result<Note[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_notes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteNote(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * FE-06: フロントの初期化が完了したらメイン画面から呼び出す。スプラッシュを閉じて
 * メインウィンドウを表示する。デスクトップ・モバイル双方の window 構成で動作する。
 */
async closeSplashscreen() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_splashscreen") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * APP-08: 自動アップデート。署名検証は tauri-plugin-updater が config の pubkey に基づき
 * 行う（CI-05 で鍵と配信マニフェストを生成する）。デスクトップのみで意味を持つ機能
 * （§3, レビュー観点 §3）。
 */
async checkForUpdate() : Promise<Result<UpdateInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * アップデートをダウンロードして適用する。呼び出し後はアプリの再起動が必要。
 */
async installUpdate() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
taskProgress: TaskProgress
}>({
taskProgress: "task-progress"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * コマンド層の統一エラー型。`app_core::CoreError` をそのまま包み、フロントには
 * serde を通じて型付きで伝わる（RS-04）。コマンド内で `unwrap()` / `expect()` は使わず、
 * 必ずこの型に変換して `Result` として返すこと（レビュー観点 §2）。
 */
export type AppError = { kind: "Core"; message: CoreError } | { kind: "Io"; message: string }
/**
 * アプリ全体で共有する統一エラー型（RS-04）。
 * 
 * `crates/core` の全ての公開関数はこの型（または個別の `thiserror` 型を経由してこの型へ
 * 変換されるもの）を返す。`src-tauri` のコマンド層はこれを `serde` でフロントへシリアライズする。
 */
export type CoreError = { kind: "InvalidInput"; message: string } | { kind: "NotFound"; message: string } | { kind: "Internal" }
export type Note = { id: number; title: string; body: string }
export type TaskProgress = { task_id: string; completed: number; total: number; status: TaskStatus }
export type TaskStatus = "running" | "completed" | "cancelled"
export type UpdateInfo = { available: boolean; version: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
